export const projects = [
  {
    id: 0,
    name: 'Document Project Manager',
    description: 'Social media site with MySQL database for users to share posts, upload files, create secure accounts, and leave comments.',
    image: 'src/assets/images/document-project-manager-img.png',
    url: 'https://document-project-manager-43ce028ce2c1.herokuapp.com/',
    githubUrl: 'https://github.com/Kiyodosan/document-project-manager',
  },
  {
    id: 1,
    name: 'Social Media API with NoSQL',
    description: 'Back-end NoSQL API with MongoDB and Mongoose that utilizes CRUD operations to store users, friends, posts, and reactions.',
    image: 'src/assets/images/social-media-api-with-nosql-img.png',
    url: 'https://drive.google.com/file/d/1tv5RoNb6MyA_9_YDjLJkn_DMfC55ImpE/view',
    githubUrl: 'https://github.com/Kiyodosan/social-media-api-with-nosql',
  },
  {
    id: 2,
    name: 'Note Maker App',
    description: 'Note-making app made with Bootstrap to create, read, and delete notes.',
    image: 'src/assets/images/note-maker-app-img.png',
    url: 'https://note-maker-app-4cd516ff3d78.herokuapp.com/',
    githubUrl: 'https://github.com/Kiyodosan/note-maker-app',
  },
  {
    id: 3,
    name: 'Demo Weather Dashboard',
    description: "A weather app made in vanilla HTML, CSS, and JavaScript that utilizes Day.js and OpenWeatherMap's Weather API. User searches for a city, then the UI displays a 7-day forecast with dynamic weather icons.",
    image: 'src/assets/images/demo-weather-dashboard-img.png',
    url: 'https://github.com/Kiyodosan/demo-weather-dashboard',
    githubUrl: 'https://github.com/Kiyodosan/demo-weather-dashboard',
  },
  {
    id: 4,
    name: 'Demo Weather Dashboard',
    description: "A weather app made in vanilla HTML, CSS, and JavaScript that utilizes Day.js and OpenWeatherMap's Weather API. User searches for a city, then the UI displays a 7-day forecast with dynamic weather icons.",
    image: 'src/assets/images/demo-weather-dashboard-img.png',
    url: '',
    githubUrl: 'https://github.com/Kiyodosan/demo-weather-dashboard',
  },
  {
    id: 5,
    name: 'Demo Weather Dashboard',
    description: "A weather app made in vanilla HTML, CSS, and JavaScript that utilizes Day.js and OpenWeatherMap's Weather API. User searches for a city, then the UI displays a 7-day forecast with dynamic weather icons.",
    image: 'src/assets/images/demo-weather-dashboard-img.png',
    url: '',
    githubUrl: 'https://github.com/Kiyodosan/demo-weather-dashboard',
  },
]